# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin

import numpy as np


# 2 - 5 elemanlı bir numpy array oluşturun

array = np.array([7, 2, 9, 4, 1])
print("Olusturulan array:", array)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.

sirali_array = np.sort(array)
print("Kucukten buyuge sirali array:", sirali_array)



Olusturulan array: [7 2 9 4 1]
Kucukten buyuge sirali array: [1 2 4 7 9]


# Problem 2

In [ ]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

import numpy as np

dizi1 = np.array([10, 15, 30, 45, 60])
print("1. Dizi:", dizi1)


# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

dizi2 = np.arange(5, 16)  # 5 dahil, 16 dahil değil
print("2. Dizi:", dizi2)
 

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

dizi3 = np.arange(50, 101, 5)
print("3. Dizi:", dizi3)


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

dizi4 = np.zeros(10)
print("4. Dizi:", dizi4)


# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

dizi5 = np.ones(10)
print("5. Dizi:", dizi5)


# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.

dizi6 = np.linspace(0, 100, 5)
print("6. Dizi:", dizi6)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

dizi7 = np.random.randint(10, 31, 5)
print("7. Dizi:", dizi7)


# 8- [-1 ile 1] arasında 10 adet sayı üretin.

dizi8 = np.random.uniform(-1, 1, 10)
print("8. Dizi:\n", dizi8)


# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

matris9 = np.random.randint(10, 51, (3, 5))
print("9. Matris:\n", matris9)


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

satir_toplamlari = matris9.sum(axis=1)
sutun_toplamlari = matris9.sum(axis=0)

print("Satir Toplamlari:", satir_toplamlari)
print("Sutun Toplamlari:", sutun_toplamlari)


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

en_buyuk = matris9.max()
en_kucuk = matris9.min()
ortalama = matris9.mean()

print("En buyuk deger:", en_buyuk)
print("En kucuk deger:", en_kucuk)
print("Ortalama:", ortalama)


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

en_buyuk_indeks = np.argmax(matris9)
print("En buyuk degerin indeksi:", en_buyuk_indeks)


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

dizi13 = np.arange(10, 21)
print("13. Dizi:", dizi13)

ilk_uc = dizi13[:3]
print("Ilk 3 Eleman:", ilk_uc)


# 14- Üretilen dizinin elemanlarını tersten yazdırın.

print("Dizinin Ters Hali:", dizi13[::-1])


# 15- Üretilen matrisin ilk satırını seçiniz.

print("Matrisin Ilk Satiri:", matris9[0])


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

eleman = matris9[1, 2]
print("2. Satir, 3. Sutundaki Eleman:", eleman)


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

ilk_elemanlar = matris9[:, 0]
print("Her satirin ilk elemani:", ilk_elemanlar)


# 18- Üretilen matrisin her bir elemanının karesini alınız.

karesi = matris9 ** 2
print("Her elemanin karesi:\n", karesi)


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

pozitif_ciftler = matris9[(matris9 > 0) & (matris9 % 2 == 0)]
print("Pozitif ve Cift Elemanlar:", pozitif_ciftler)


1. Dizi: [10 15 30 45 60]
2. Dizi: [ 5  6  7  8  9 10 11 12 13 14 15]
3. Dizi: [ 50  55  60  65  70  75  80  85  90  95 100]
4. Dizi: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5. Dizi: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6. Dizi: [  0.  25.  50.  75. 100.]
7. Dizi: [25 26 24 16 15]
8. Dizi:
 [ 0.41978094  0.07701569  0.37317944  0.49437777  0.27971236 -0.85716789
  0.87350355  0.89027386 -0.29631295  0.19939305]
9. Matris:
 [[23 40 33 30 29]
 [20 20 31 47 15]
 [43 41 43 37 40]]
Satir Toplamlari: [155 133 204]
Sutun Toplamlari: [ 86 101 107 114  84]
En buyuk deger: 47
En kucuk deger: 15
Ortalama: 32.8
En buyuk degerin indeksi: 8
13. Dizi: [10 11 12 13 14 15 16 17 18 19 20]
Ilk 3 Eleman: [10 11 12]
Dizinin Ters Hali: [20 19 18 17 16 15 14 13 12 11 10]
Matrisin Ilk Satiri: [23 40 33 30 29]
2. Satir, 3. Sutundaki Eleman: 31
Her satirin ilk elemanı: [23 20 43]
Her elemanin karesi:
 [[ 529 1600 1089  900  841]
 [ 400  400  961 2209  225]
 [1849 1681 1849 1369 1600]]
Pozitif ve Cift Elemanlar: [40 30 20 20